### ISSUE TITLE
[HD][Report]Informal Waste worker registration data

### ISSUE THREAD

**Issue by nubrapika** [avniproject/hasiru-dala#11]
The report will contain all the elements from 
1. Common Registration form
2. Common Waste Worker

Ind.UUID should also be a field

Form elements are here: 
https://docs.google.com/spreadsheets/d/1Un8RnBUEAnWFn9HA_5E3peClhkjSdaweytdViU7Bfj0/edit

**Comment by garimadosar5** [comment]
QA Notes - 
- In `Registration Details` and `Common Registration Details`, one individual is coming more than once.
-

**Comment by sidsamanvay** [comment]
@garimadosar5 @sidsamanvay 

now, showing ID,UUID,Name in [[Not Released/Do not use] Informal Waste Worker](https://reporting.openchs.org/question/501) report.
