### ISSUE TITLE
[HD] Feedback from UAT

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#14]
https://docs.google.com/spreadsheets/d/1ILdRAYekFpjZTL-b9Lu93Hu5JDRa3_G7/edit#gid=1966369409
Feedback - 
- "Identification" question "ID1 - Do you have any of the following?" options - Aadhar and Aadhar Enrolment ID can not be selected together. _NOT DONE_
- Qus - B2 - "Please upload the picture of the duly filled consent form" - make it mandatory. - _DONE_
- Section "Introduced by" - make it mandatory. _DONE_
- Section - Disablement, If D1 is answered as YES, make D1.1 and D1.2 mandatory. _DONE_
- Section "Social Security" - Do you get old-age pension (OAP)? skip is not working.  _DONE_
- Age should take only numbers. -- [Arjun] Age opens up number pad only. How are they entering non-numbers? -- Not doing anything related to this right now. 
- In relationship add daughter-in-law and son-in-law. -- Done (Arjun)
- In Section "work address", make contact number 2 - non-mandatory. - _DONE_
- When adding the individual as SON/Daughter. The app is crashing. [Arjun will work on this] -- Done
- It should not allow self-relationship.[Arjun will work on this] -- Done

##### QA Notes - 
- Make a few Questions Mandatory. (Marked in Red in the spreadsheet).
- "Present Address" Make "Contact number" 2 as non-mandatory. _DONE_
- If we go back and change the type of Respondent, The flow does not change. 
- Section Identification - If the question "Whether you have Aadhar Card" is answered as YES. skip the question "Do you have Aedhar Enrollment ID". _NOT DONE_
- Change in the flow of Common Sanitation worker. (Changes are highlighted in 'RED') _DONE_
https://docs.google.com/spreadsheets/d/1Un8RnBUEAnWFn9HA_5E3peClhkjSdaweytdViU7Bfj0/edit#gid=1476457617

**Comment by arjunk** [comment]
@garimadosar5 @shubhangipatil Deployed latest HD to staging. Also this is the latest APK for platform fixes :  https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0aa1-2019-09-19-12-48-26.apk

**Comment by garimadosar5** [comment]
@shubhangipatil  
Registration Observation in Profile - 
- It shows in random order.
- If the data is cleared from the device and again login, then `Consent form image` does not get downloaded and if you again edit the form, it ask for the 'form image' again.
