### ISSUE TITLE
[HD] Changes after UAT testing.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#17]
https://docs.google.com/spreadsheets/d/1Un8RnBUEAnWFn9HA_5E3peClhkjSdaweytdViU7Bfj0/edit#gid=301651717

###### Common Registration -  2 hours
1. Change the language of options for R1 and EM1. (Group 'Respondent Type' and 'Employment')
2. Group - Disablement,  Remove question D2 and D2.1
3. Group - Profession, Question P3, Change one option.
4. Group - Health and sanitation, Question HS1, Add some options in the question.
5. Group - Health and sanitation, Question HS2.1, Add some options in the question.
6. Group - Financial Inclusion, Change the language of questions FI1.1, FI1.2, FI2.1, FI2.2, FI3.1, FI5.1, FI7.2, FI8.1.
- Make Red marked as mandatory/Non-mandatory.
###### Common Waste Worker - 1 hour
1. Group - Profession, Question P2, add one option.
2. Group - Training, add questions.  
###### Common Sanitation Worker - 1 hour
1. Group - Profession, Add one option in question P2. 
2. Add one logic Given in BO1.
###### Toilet Cleaner - 1 hour
1. Group - Toilet Cleaner, Question 6. Change the option and logic.
2. Group - Toilet Cleaner, Question 9. Change the option and logic.
###### Waste picker - 30 mins
1. Question 4d - Change the language od question.
2. Question 6 - Make it multi select.
###### SWM DTDC
1. Make all the question mandatory.
###### SWM Sweeper
1. Make all the question Mandatory.
###### Desludging Worker - 1.5 hours
1. Make all the question mandatory.
2. Change the option and logic for question 3.
3. Change the option and logic for question 9, 10, 10.1, 7, 12, 13, 13.1, 13.2, 13.3, 14, 14.1, 14.2, 14.3.
###### Decanting Worker - 30 mins
1. Make all the question mandatory.
2. Change the option for question 10.

`Change are highlighted in the red`.

**Comment by vindeolal** [comment]
Deployed changes in staging.

**Comment by garimadosar5** [comment]
QA Notes - 
- Relative profession needs to be mandatory.
- Group 'Housing', H1, H2 needs to be mandatory.
- Group 'Profession', P3 needs to be mandatory and there is a change in an option.
- Group 'Occupational Safety', needs to be mandatory.
- In the case of Informal waste worker, group 'Training' - question - Please select from the list. Options are coming as UUIDs. (and it needs to be multi-select).
- Now there are two groups as training for Informal waste worker.
- The questions where we have changed the option from YES/NO to ALWAYS/SOMETIMES/NEVER/ NO Response, in all these questions, all the options are coming. (YES/NO/ALWAYS/SOMETIMES/NEVER/UUIDs).

**Comment by garimadosar5** [comment]
Technical.
1. SWM SWEEPER - Income - Question 8. Skip is not working.
2. DESLUDGING WORKER - Question Number 9 Remove the skip logic and Question Number 10 should be made compulsory. 
3. COMMON REGISTRATION - Profession - P9 Mode of Payment - should be made compulsory- and remove the 
4. COMMON REGISTRATION - SOCIAL SECURITY - SS1 Old Age Pension 60 yrs. (Logic is not working)

Lokalise Translated keys
1. Individual
2. ULB
3. Mode of Payment
4. Who hands over the cash/ cheque or makes the money transfer?
5. Identification
6. Have you received assistance from any Government body ( Ex. TAHDCO, SLUM BOARD)?
