### ISSUE TITLE
Create sub-domains for DWCC and library application

### ISSUE THREAD

**Issue by petmongrels** [avniproject/hasiru-dala#2]
Proposed names to be confirmed by Hasiru Dala.
dwcc.hasirudala.org, buguri.hasirudala.org, reporting.hasirudala.org and mis.hasirudala.org (mis will be used just for the home page where the user can navigate to individual apps, more detail in other stories)

**Comment by charl3sj** [comment]
- Instead of dwcc, how about mis.hasirudala as a kitchen sink for everything including DWCC?
- library sub-domain could be called "buguri" instead after its actual name.
