### ISSUE TITLE
[HD][Report] Report for Dependent Relatives.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#20]
1. Create a report named "Individuals neither informal worker nor linked to informal worker" to list all such individuals
2.  In app displace in program summary of the individual "Neither informal worker nor linked to any informal worker" in red colour. 
- Logic would be: to get all the individuals who don't satisfy both the following condition
    1. Answer to "Type of respondent" question is Registration is not "Informal Worker"
    2. Condition 1 is not true for any individual linked to this individual via relationship

### Tech Task
- [x] Create report
- [x] Add summary

**Comment by garimadosar5** [comment]
QA Notes - 
- In the column "Type of worker (Relative)", relation is coming like this ["Relative Living with Worker / Informal Worker (Dependent)","Relative Living with Worker / Informal Worker (Dependent)"]
remove quotes and [].

**Comment by arjunk** [comment]
@sachsk @garimadosar5 anything pending to close this?
