### ISSUE TITLE
[App][Bug] Translations are not showing for few strings.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#29]
Translation String- 
- Don't Know
- FI10.1 - Are you registered with  Employees’ State Insurance (ESI)? (In observation table)
- Options of Qus - P1 
1)  Self Employed – Operate their enterprise, may hire helper
2)  Contract – Payment received is other than daily wage / hour rate (Weekly / Fortnightly / Monthly) through contractor or establishment, though calculations maybe based on daily rate/hours
3)  Employee – Employed with government or private organization, having social security benefits
4)  Daily wage – Payment is received daily / hour rate

**Comment by sachsk** [comment]
@garimadosar5 
Fixed and Deployed on Staging And UAT
