### ISSUE TITLE
Setup codebase for DWCC

### ISSUE THREAD

**Issue by petmongrels** [avniproject/hasiru-dala#3]
Hasiru Dala project has two more applications apart from social security application for social workers in the field which is based on OpenCHS. DWCC and Library are two additional web applications with their own database.

We plan to use the following tech stack for this - postgresql, spring, react, react-admin in embed mode.

Setup four GitHub repositories with the boilerplate code necessary. Create a Github organisation for HD.
1. dwcc-web
2. dwcc-server

For server project use the latest stable versions of - Java, Spring and PostgreSQL. Use the Spring boot's mechanism for setting up a new project. Also setup logging, database connection (using JPA, Hibernate) and Flyway.
Items
- Logging (DONE)
- Flyway (DONE)
- Hello Controller (DONE)
- Bugsnag

For web project use the latest stable versions of - React, React Admin. React Admin should be in the embed mode (the way it has been done in OpenCHS). Do not add login functionality.

Create Bugsnag account and setup Bugsnag on both servers and both web apps.

**Comment by charl3sj** [comment]
Bugsnag integration is also complete.
