### ISSUE TITLE
[HD] State specific schemes to be shown only if local ID is there

### ISSUE THREAD

**Issue by arjunk** [avniproject/hasiru-dala#30]
The state-specific schemes will be shown in the "Facilitation form" based on the following logic - 
- If in the Enumeration form(Registration), the question MigAd1 "Do you have any local address proof?" is answered as YES, then State specific schemes will be shown. If the question is answered as NO, state schemes will not be shown.

**Comment by vindeolal** [comment]
Added new Key/value to make a scheme state specific
`key` : `stateSpecific` and `value`: `yes`.
Any scheme with this key/value will not show up for an individual in start facilitation unless question from registration `Do you have a local address proof?` is not answered `Yes`.

In staging `Caste Certificate` is state specific scheme.

**Comment by garimadosar5** [comment]
QA Notes-
- State-specific scheme is showing for the person "local id" is not available.
Login - staging@hasiru/password
Case - First hasiru
Scheme - Caste Certificate State

Please check.
