### ISSUE TITLE
[HD][SS] Change in decision rule and visit scheduling.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#31]
Visit Scheduling and Decision Rule Change - 
- Document Collection Cancellation
- Submit Application
- Enquire Application Status
- Application submission cancellation
- Application status enquiry cancellation.

Change in the Registration form -  **DONE**
- Group - Migration Address proof 
Skip is not working.
1) The question "Please select the type of local address proof" should be shown if "Do you have a local address proof?" is answered as YES.
2) The question "Name of the ID" and "Description" should be shown if "Please select the type of local address proof" is answered as "Other"

**Comment by garimadosar5** [comment]
QA Comment - 
- When we are takings ids/schemes to show in "Update details", we should pick ids from the question group - "Local id proofs"
-

**Comment by vindeolal** [comment]
@garimadosar5 
1. Not done as of now.
2. Fixed
3. Fixed. (Right now only few schemes are added in future if we need to add a new scheme which is not there in concept answer please add to below concepts `Enroll Scheme,
Register scheme,
update scheme,
Scheme`)
4. fixed
5. fixed (right now we don't schedule workflow for recurring schemes)
