### ISSUE TITLE
[HD][TN] Link is missing for some images.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#32]
In some cases where images are uploaded, links are not there in the system. Only the name of the image is there.
Need to check what has happened and what can be done to resolve this.

Maybe we need to ask them to re-upload the image and sync.

**Comment by vindeolal** [comment]
Cases with missing images : https://reporting.openchs.org/question/652
We need to release the app and user need to sync again, so that image get uploaded to S3.
