### ISSUE TITLE
[HD] Change in enumeration form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#34]
type "Street Sweeper/Drain Cleaner" from the Informal Waste Worker Category to Informal Sanitation Worker Category.

Ref doc - https://docs.google.com/spreadsheets/d/1Un8RnBUEAnWFn9HA_5E3peClhkjSdaweytdViU7Bfj0/edit#gid=1476457617

Sheet "common Waste Worker" qus -1, remove option "Street Sweeper/Drain Cleaner" and put this option in the qus - 1 "Common sanitation Worker".

- The change should be in both TN and KA implementation.
- Deploy this change in both staging and UAT.

**Comment by sachsk** [comment]
@garimadosar5 
Deployed on staging and UAT

**Comment by garimadosar5** [comment]
QA Notes - 
- SVM sweeper sheet questions are not showing up.
