### ISSUE TITLE
[HD][Report] Line List of Enumeration

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#35]
https://docs.google.com/spreadsheets/d/1Ny8jSKTox884-oCKraJgWAdGGFzSdx4DHujIsTMQzck/edit#gid=1365314164

**Comment by vindeolal** [comment]
Added required filters in the report 
Link : https://reporting.openchs.org/question/500

**Comment by garimadosar5** [comment]
QA notes - 
- Voided wards are also showing in the filter.
-
