### ISSUE TITLE
[HD][Report] Enumeration as on Date

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#36]
https://docs.google.com/spreadsheets/d/1Ny8jSKTox884-oCKraJgWAdGGFzSdx4DHujIsTMQzck/edit#gid=1365314164

**Comment by vindeolal** [comment]
Report link : https://reporting.openchs.org/question/730

**Comment by garimadosar5** [comment]
QA Notes- 
- Please remove time from date.
