### ISSUE TITLE
[HD][Report] Waste Collection Report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#37]
https://docs.google.com/spreadsheets/d/1Ny8jSKTox884-oCKraJgWAdGGFzSdx4DHujIsTMQzck/edit#gid=763709240

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**Comment by garimadosar5** [comment]
QA Notes - 
- "Type of Waste" column is missing.
- Data seems to be wrong. In scrap dealer, we have added question recently but it is giving the value for Feb 2020 also. Please check once.

**Comment by sachsk** [comment]
https://reporting.openchs.org/question/784

**Comment by garimadosar5** [comment]
@sachsk  this is good. Move it to HD prod and in their collection.
There is already a report - https://reporting.openchs.org/question/745. replace this report with new one.

**Comment by sachsk** [comment]
@garimadosar5 report is moved on prod. and moved to 'hasiru dala tn' collection
