### ISSUE TITLE
[HD] Add question in Scrap dealer type worker.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#40]
S. No - 10. Details of waste sold per week (in Kg).

Add in both TN and KA.

https://docs.google.com/spreadsheets/d/1Un8RnBUEAnWFn9HA_5E3peClhkjSdaweytdViU7Bfj0/edit#gid=349656667

**Comment by garimadosar5** [comment]
QA Notes - 
- Remove the question "Details of waste sold per week" - This is a group only.
- Remove "Other" from the questions "Other Rubber", "Other Textile/Rage", "Other Tin" and "Other Thermocol".
- Remove Question "Thermocol/Styrofoam Deatails".
- Add one more question - "If any other waste is sold, please mention the quality waste sold per week".

![Screen Shot 2020-04-01 at 9.29.03 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/222f3b54-ea9a-42eb-a0f6-00adee764e3a)

**Comment by sachsk** [comment]
chnages deployed on staging of TN & KA

**Comment by garimadosar5** [comment]
QA Notes - 2
- Change Question - "White plastic details" to "If any other plastic is sold, please mention the quantity in sold per week". data Typer - numeric.
- Change Question - "Tetrapack details" to "If any other paper is sold, please mention the quantity in sold per week". data Typer - numeric.

**Comment by garimadosar5** [comment]
@sachsk  Please move it to prod.
