### ISSUE TITLE
[HD] Eligibility Criteria for SS Schemes.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#43]
https://docs.google.com/spreadsheets/d/1YuxTQh67d-mTFZfo1RHKvvEPr_n22sTq/edit?dls=true

**Comment by vindeolal** [comment]
Please find the key/value used for each criteria in the scheme concept. We need to use the same key/value for the new schemes that will get added.

![image.png](https://images.zenhubusercontent.com/5d0b116e2fff8629577fc2d4/e1591d5b-1c3e-4022-8c9f-894e7ae24841)

A new scheme needs to be added to the below concepts as an answer.
- Scheme
- Register scheme 
- Update scheme 
- Enroll scheme

All the schemes for the sheet are added and deployed in staging.
