### ISSUE TITLE
[HD] UAT feedback II

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#49]
https://docs.google.com/spreadsheets/d/1ILdRAYekFpjZTL-b9Lu93Hu5JDRa3_G7/edit#gid=1966369409

- **Row 84** -  "If a person is exited from program then new program enrolment option should not show.
If user wants to again enrol then they will do undo Exit and continue."

- **Row 87** - "What happens if recurring has ended and user wants to again start the facilitation. for that scheme.
We need to add the recurring in Start Facilitation list once ""facilitation ended""."

- **Row 83** - Relative Report - Some cases are showing that are linked to "Informal Worker". Check for the first and second case in the list. Report - https://reporting.avniproject.org/question/1170

- **Row 80** - When a recurring scheme is chosen is started from "Register already availed scheme" workflow, it takes you to "Start Recurring Facilitation" form and then takes you to the page where it again lists all the recurring schemes.  The option to enter the first recurring facilitation date needs to be made available in the first form itself.

- **Row 76** - If an eligilbility criteria (like Bank A/C or Aadhar Card) gets satisfied during SS facilitation, the scheme list should also get updated.

**Comment by vindeolal** [comment]
Changes are done on staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-b2f5d-2020-09-02-14-56-55.apk
