### ISSUE TITLE
[HD] add individual profile summary

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#51]
Add a Note/message in profile summary
- if in individual reg Respondent Type: "Relative Living with Worker / Informal Worker (Dependent)" or "Relative Living with Worker / Informal Worker (Not Dependent)". and not related to anyone with respondent type is "Informal worker".

Message: Please add an Informal worker as relative.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- I cannot see the message on UAT (garima@hdtnuat/password)
**cases -** 
1. Ram Simra
2. Register Indi

**Comment by sachsk** [comment]
Please use these APK for testing
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-57187-2020-09-11-09-46-58.apk
