### ISSUE TITLE
[HD] Changes in Enumeration form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#53]
- Changes mentioned in column J (highlighted in Blue).

doc - 
https://docs.google.com/spreadsheets/d/1XN456T6s34Kv9dQTWR2uiEpYNqcAHGUO/edit#gid=37639766

**Comment by sachsk** [comment]
@garimadosar5 Changes made on HDTNUAT

**Comment by garimadosar5** [comment]
QA Notes - 
- All the questions where the image needs to be attached, if we select the image from the existing folder it does not attach that image. It works when the image is clicked at that time.
