### ISSUE TITLE
New organisation for Migrants

### ISSUE THREAD

**Issue by arjunk** [avniproject/hasiru-dala#64]
- [x] - New Organisation name - Waste Workers Association

- [x] - Locations for this org - 

•  All the locations from Bangaluru City
• All the locations from Mysore City
• All the locations from Mangalore City

https://docs.google.com/spreadsheets/d/1rumFTDnrAJVDxZPFpOADMbYjU30530LsXf0gQxi1zuU/edit#gid=1249269638

**Comment by sachsk** [comment]
Registration form:
Please select the reason(s) for discontinuation: no response should be unique

**Comment by utkarshavni** [comment]
Tested on Prod - Working fine.
