### ISSUE TITLE
Misc Tasks - Aadhar, PAN card and more

### ISSUE THREAD

**Issue by arjunk** [avniproject/hasiru-dala#67]
- [x] Add new fields in Enumeration for Aadhar and PAN card
- [x] Introduce the same fields in Search
- [x] Offline report for facilitators to know how many entries they have done in the current month
- [x] Add rural locations
New location doc - https://docs.google.com/spreadsheets/d/1rumFTDnrAJVDxZPFpOADMbYjU30530LsXf0gQxi1zuU/edit#gid=1518189343
- [x] Catchment for urban and rural together
Ref doc - https://docs.google.com/spreadsheets/d/1rumFTDnrAJVDxZPFpOADMbYjU30530LsXf0gQxi1zuU/edit#gid=636980242

**Comment by nupoorkhandelwal** [comment]
Location details have not been shared yet.
