### ISSUE TITLE
Entries against catchment with no locations to be moved to correct Catchment.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/hasiru-dala#73]
Below given are the catchments with no locations.

Hubli - Dharwad 

There are two entries of this catchment with one of them having no locations against it. There are entries recorded against that catchment. Those entries have to be disassociated from that catchment and moved to the right catchment which has locations under it.

**Comment by utkarshavni** [comment]
Ticket has been raised for the issue:
https://avni.freshdesk.com/a/tickets/1686

It has been merged with ticket # 1685 which is facing similar issue:
https://avni.freshdesk.com/a/tickets/1685

For 1685: There are two locations for the state Andhra Pradesh - one is "ANDRA PRADESH" and the other is "Andhra Pradesh". ANDRA PRADESH does not have any child locations but it is part of a catchment "Rajamahendravaram" which has entries. The correct location under the catchment should be Rajamahendravaram city only and entries need to be migrated there.

**Comment by nupoorkhandelwal** [comment]
-- 63262	Andhra Pradesh
-- 53594	ANDRA PRADESH
-- Script to migrate data from ANDRA to Andhra
set role hasiru_karnataka;
update individual
set address_id = 63262,
    last_modified_date_time = current_timestamp ,
    last_modified_by_id = (select id from users where username = 'nupoork@hd_ka')
where address_id = 53594;

**Comment by utkarshavni** [comment]
Removed Hubli- Dharwad location. Data is displayed against correct location which is Hubli-Dharwad. 

Data id displayed correctly against Andhra Pradesh location now for Rajamhendravaram. Removed Andra Pradesh location. Added Andhra Pradesh location in Rajamhendravaram location type and under the catchment.
