### ISSUE TITLE
[Hasiru Dala] Avail Service encounter for Social Security Program

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/hasiru-dala#76]
**Motivation:**
After enrolment of beneficiaries into the program, user is required to select the type of scheme beneficiary is availing service for and update details after communication with beneficiary as well as acknowledgement of service received has been done.

Create a Program encounter named "Avail Service"
Form Name - "Avail Service".

No eligibility check on encounter is required.

Form Requirement:
https://docs.google.com/spreadsheets/d/1L8fs4PJdvxk9aG4y4Z6dM_khxVx3x7DqlZ0KHeeLntI/edit#gid=0

**Comment by utkarshavni** [comment]
- [ ] General Social Security schemes are not populated in the Avail services encounter.

**Comment by Gojo-Taqi** [comment]
They only populate if they satisfy the conditions.
For example, if aadhaar id is defined, local id is defined, and marital status is defined, then the programs which the person is eligible shall appear.
